<?php
    namespace Database\Seeders;
    use App\Models\peliculas;
    use Illuminate\Database\Seeder;

    class PeliculasTableSeeder extends Seeder {
        public function run(): void {
            $peliculas = [
                ["nombre_pelicula" => "El Lobo de Wall Street",   "disponible" => true, "categoria_id" => 1, "data" => today(), "descripcion" => "Basada en la vida real de Jordan Belfort, esta película dirigida por Martin Scorsese sigue la ascensión y caída de un corredor de bolsa en Wall Street, quien se enriquece a través del fraude y la corrupción, pero su estilo de vida decadente lo lleva a enfrentarse con la ley.", "imagen" => "peliculas/1742543260-MV5BY2Y2YmM1NmUtY2M2YS00Mjg1LWI0MDAtYzhlNzUyMjdjZGZjXkEyXkFqcGc@.webp", "preu_entrada" => "6"],
                ["nombre_pelicula" => "American Psycho",          "disponible" => true, "categoria_id" => 2, "data" => today(), "descripcion" => "Un thriller psicológico que sigue a Patrick Bateman, un ejecutivo de Wall Street obsesionado con el éxito, la imagen y el materialismo, mientras lucha con su oscura y violenta naturaleza psicópata en la Nueva York de los años 80.",                                               "imagen" => "peliculas/1742543811-MV5BNTA3N2Y4MzktYjBkYi00ZDk3LWJlMDUtODc1NzFiYmMxMjFhXkEyXkFqcGc@.webp", "preu_entrada" => "6"],
                ["nombre_pelicula" => "Baby Driver",              "disponible" => true, "categoria_id" => 3, "data" => today(), "descripcion" => "Un joven conductor especializado en fugas, conocido como Baby, se ve obligado a trabajar para un jefe del crimen. Con una banda sonora electrizante y persecuciones llenas de adrenalina, Baby intenta escapar del mundo criminal para proteger a la mujer que ama.",                 "imagen" => "peliculas/1742543920-baby-driver.jpg.webp"                                                 , "preu_entrada" => "6"],
                ["nombre_pelicula" => "El correo",                "disponible" => true, "categoria_id" => 1, "data" => today(), "descripcion" => "Dirigida por Clint Eastwood, esta película cuenta la historia real de un mensajero que transporta paquetes sospechosos y se ve envuelto en una red de crimen organizado.",                                                                                                            "imagen" => "peliculas/1742544176-el-correo-poster-65ae891f483b8.webp"                                  , "preu_entrada" => "6"],
                ["nombre_pelicula" => "Interestelar",             "disponible" => true, "categoria_id" => 2, "data" => today(), "descripcion" => "Una odisea espacial dirigida por Christopher Nolan que sigue a un grupo de astronautas en una misión para encontrar un nuevo hogar para la humanidad mientras enfrentan los misterios del tiempo y el espacio.",                                                                      "imagen" => "peliculas/1742544530-48727.webp"                                                           , "preu_entrada" => "6"],
                ["nombre_pelicula" => "Inception",                "disponible" => true, "categoria_id" => 3, "data" => today(), "descripcion" => "Un ladrón que roba secretos a través de los sueños es contratado para implantar una idea en la mente de un empresario, en una película que desafía la percepción de la realidad.",                                                                                                    "imagen" => "peliculas/1742544619-inception_keyart.webp"                                                , "preu_entrada" => "6"],
            ];

            peliculas::insert($peliculas);
        }
    }